// Static search topics for Microsoft Rewards Auto-Claimer
// Enhanced with diverse, human-like query variations across multiple categories

self.SEARCH_TOPICS = [
  // ── Technology & AI ──
  "latest smartphone reviews 2026",
  "best laptop for programming and web development",
  "how to build a modern web application",
  "artificial intelligence breakthrough news",
  "machine learning tutorials for beginners step by step",
  "best programming languages to learn this year",
  "cybersecurity tips for remote workers and small business",
  "cloud computing architecture benefits explained",
  "quantum computing algorithms research paper",
  "smart home automation hub setup guide",
  "virtual reality headset comparison 4k",
  "augmented reality applications in healthcare",
  "data science portfolio project ideas",
  "TypeScript vs JavaScript performance difference",
  "React vs Vue vs Svelte framework benchmark",
  "Docker containerization best practices tutorial",
  "Kubernetes cluster setup step by step",
  "serverless architecture advantages and tradeoffs",
  "microservices design patterns REST vs gRPC",
  "modern database indexing and query optimization",
  "web performance optimization Core Web Vitals",
  "open source developer tools github trending",
  "next generation battery technology solid state",
  "edge computing architecture IoT devices",
  "zero trust security architecture implementation",
  "autonomous vehicles computer vision advances",
  "generative AI prompting techniques and models",
  "Rust programming memory safety explained",
  "Go vs Rust for backend microservices",
  "Linux command line productivity shortcuts",

  // ── Health, Wellness & Nutrition ──
  "morning workout routine for energy and flexibility",
  "healthy meal prep ideas for busy work weeks",
  "yoga poses for lower back pain relief",
  "intermittent fasting science and benefits guide",
  "running shoe recommendations marathon training",
  "mindfulness meditation exercises for stress reduction",
  "circadian rhythm sleep improvement techniques",
  "calisthenics progression guide for beginners",
  "plant based protein sources complete amino acids",
  "strength training without weights at home",
  "ergonomic desk setup prevent neck strain",
  "daily hydration water intake calculator",
  "magnesium and vitamin D sleep quality research",
  "high intensity interval training 20 minute session",
  "anti inflammatory Mediterranean diet recipes",
  "proper breathing exercises anxiety relief",
  "mobility exercises hip flexor tightness",
  "healthy smoothie bowl recipes antioxidants",
  "tracking HRV heart rate variability recovery",
  "posture correction exercises upper body",

  // ── Science, Space & Nature ──
  "James Webb Space Telescope latest deep space images",
  "Mars rover sediment sample analysis",
  "renewable solar energy storage innovations",
  "ocean floor hydrothermal vent ecosystems",
  "timeline of human space exploration milestones",
  "how CRISPR Cas9 gene editing works explained",
  "exoplanet atmospheric detection habitable zone",
  "deep sea bioluminescence species discovery",
  "gravitational waves detection laser interferometry",
  "black hole event horizon telescope findings",
  "photosynthesis quantum biology mechanisms",
  "plate tectonics earthquake early warning systems",
  "volcano monitoring satellite radar data",
  "biodiversity conservation rain forest corridors",
  "aurora borealis northern lights forecast guide",
  "coral reef restoration marine biology projects",
  "fusion energy net energy gain experiments",
  "neuroplasticity brain learning adaptation",
  "geothermal energy plant efficiency",
  "microplastics filtration ocean cleanup technology",

  // ── Entertainment, Cinema & Gaming ──
  "top rated films streaming this month",
  "critically acclaimed sci fi novels 21st century",
  "indie video games soundtrack design",
  "retro gaming console restoration guide",
  "creative storytelling techniques world building",
  "documentary films about wildlife conservation",
  "acoustic guitar fingerstyle tutorial beginners",
  "piano chord progressions emotional music",
  "photography composition rule of thirds golden ratio",
  "digital art drawing tablet comparison",
  "unreal engine 5 lighting lumen tutorial",
  "board games strategy game night recommendations",
  "soundtrack composers orchestra scoring",
  "animation history hand drawn to 3D CGI",
  "behind the scenes film cinematography lighting",
  "audiobook narration recommendations fiction",
  "stand up comedy specials writing process",
  "video editing color grading tutorial Davinci",
  "screenplay formatting structure three act",
  "virtual reality gaming immersive experiences",

  // ── Travel, Culture & Adventure ──
  "scenic train routes around the world",
  "sustainable eco tourism travel destinations",
  "packing light carry on bag 2 week trip",
  "hiking national parks trail navigation guide",
  "architectural marvels modern ancient wonders",
  "cultural festivals history around the globe",
  "solo travel safety guide tips for beginners",
  "hidden gems travel destinations Europe",
  "kayaking coastal routes wildlife watching",
  "mountain passes cycling routes scenic views",
  "historical landmarks UNESCO world heritage sites",
  "astrophotography night sky dark sky parks",
  "best botanical gardens visit world",
  "island hopping itinerary Mediterranean",
  "campervan road trip planning budget guide",
  "street food cultures markets worldwide",
  "scuba diving coral reef conservation tours",
  "traditional crafts pottery weaving workshops",
  "Nordic fjords hiking trails summer",
  "alpine lakes photography scenic landscapes",

  // ── Gastronomy & Culinary Arts ──
  "sourdough bread baking hydration ratios",
  "french pastry techniques croissant lamination",
  "authentic Neapolitan pizza dough 48 hour ferment",
  "fresh pasta making flour eggs ratio",
  "coffee roasting profiles pour over brew methods",
  "matcha green tea ceremony preparation",
  "fermented foods kimchi sauerkraut gut health",
  "sous vide cooking temperatures steak guide",
  "knife sharpening whetstone techniques",
  "herbs and spices pairing flavor wheel",
  "caramelization Maillard reaction cooking chemistry",
  "vegan dessert baking egg substitutes",
  "artisan cheese making process milk types",
  "seasonal farm to table vegetable recipes",
  "tea brewing water temperature extraction",
  "homemade bone broth slow simmer recipe",
  "chocolate tempering guide glossy finish",
  "wok cooking high heat technique wok hei",
  "fresh herb garden windowsill indoor",
  "smokehouse BBQ wood flavors temperature control",

  // ── Finance, Productivity & Learning ──
  "compound interest investment growth calculator",
  "index funds long term portfolio diversification",
  "budgeting spreadsheet 50 30 20 rule template",
  "emergency savings fund building step by step",
  "time blocking productivity calendar technique",
  "Pomodoro technique focus workflow study sessions",
  "deep work habits elimination of digital distraction",
  "speed reading comprehension retention techniques",
  "second brain digital note taking system",
  "critical thinking logical fallacies list",
  "public speaking confidence vocal projection tips",
  "negotiation strategies win win outcomes",
  "personal finance literacy books essentials",
  "mind mapping visual brainstorming methods",
  "habit stacking atomic habits routine building",
  "retention flashcard spaced repetition Anki",
  "passive income streams realistic breakdown",
  "side project management Kanban workflow",
  "decision making framework first principles thinking",
  "effective email writing concise professional",

  // ── Architecture, Home & Eco Living ──
  "biophilic architectural design natural light",
  "minimalist interior design functional aesthetics",
  "indoor houseplants air purifying low maintenance",
  "permaculture garden design raised beds companion planting",
  "zero waste kitchen habits sustainable alternatives",
  "energy efficient home insulation solar heat gain",
  "rainwater harvesting system setup DIY",
  "composting kitchen scraps worm farm guide",
  "woodworking joinery techniques beginners",
  "smart home energy monitor tracking consumption",
  "mid century modern furniture design history",
  "passive house architecture heating principles",
  "vertical garden wall DIY indoor irrigation",
  "natural lighting interior layout tips",
  "decluttering KonMari method organizing home",
  "restoring vintage wooden furniture sanding stain",
  "sustainable building materials rammed earth timber",
  "hydroponic indoor herb garden led grow lights",
  "acoustic room treatment podcast recording setup",
  "compact home workspace ergonomic layout"
];

// Helper to provide humanized query variations with natural search phrasing
self.getHumanizedSearchQuery = function() {
  const topics = self.SEARCH_TOPICS;
  const base = topics[Math.floor(Math.random() * topics.length)];
  const prefixes = ["", "", "", "how to ", "what is ", "best ", "guide to "];
  const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
  
  if (prefix && !base.toLowerCase().startsWith("how") && !base.toLowerCase().startsWith("what") && !base.toLowerCase().startsWith("best")) {
    return prefix + base;
  }
  return base;
};
